### ISSUE TITLE
phpFastCache getPath params

### ISSUE THREAD

**Issue by str** [10quality/wpmvc-mvc#22]
In the WPMVC\PHPFastCache\phpFastCache class, the getPath method has 2 params.

```php
public static function getPath($skip_create_path = false, $config) {
    // ...
}
```
The first param is optional, but the first one is required. It's not possible to leave the first param unset. This is flagged as a deprecated error message starting from PHP 8.0. This is a link documenting the error message: https://php.watch/versions/8.0/deprecate-required-param-after-optional

The error can be find in the file 10quality/wpmvc-phpfastcache/src/psr4/phpFastCache.php line 113

**Comment by amostajo** [comment]
Moved here https://github.com/10quality/wpmvc-phpfastcache/issues/2
