### ISSUE TITLE
How to show view in #wp-content div of the wordpress admin dashboard ?

### ISSUE THREAD

**Issue by temuujina** [10quality/wpmvc-mvc#27]
There is a #wpwrap and #wpcontent divs in body of the wordpress html.
```
<div id="wpwrap">
  <div id="wpcontent">
     ``
  <div>
<div>
```

When I call this function 
`$this->view->show('circulation.circulation', [] );`

my view file which is .php file appears just below the body tag where is above the #wpwrap div.
How to show view .php file in #wpcontent div ?

**Comment by amostajo** [comment]
There are two ways to do it.

----

**OPTION 1) Using global method**

If you are using a theme, call the `theme()` global method:
```html
<?php theme()->view( 'circulation.circulation' ); ?>
<div id="wpwrap"><div>
```

If you are using a plugin:
```html
<?php getBridge( '[PLUGIN NAMESPACE]' )->view( 'circulation.circulation' ); ?>
<div id="wpwrap"><div>
```

----

**OPTION 2) By adding a custom hook**

You need to add a WordPress action hook above your div, for example:
```html
<?php do_action( 'above_wpwrap' ); ?>
<div id="wpwrap">
  <div id="wpcontent">
     ``
  <div>
<div>
```

Then use a controller/view handler with following command:
```dash
php ayuco add action:above_wpwrap view@circulation.circulation
```
